### ISSUE TITLE
Tracking issues from version 3

### ISSUE THREAD

**Issue by chfoo** [ArchiveTeam/warrior4-vm#1]
This is issue is for tracking past issues for first stable release of version 4.

Issues from version 3 that are being addressed:

- [ ] https://github.com/ArchiveTeam/Ubuntu-Warrior/issues/26
- [ ] https://github.com/ArchiveTeam/Ubuntu-Warrior/issues/19
- [ ] https://github.com/ArchiveTeam/Ubuntu-Warrior/issues/22
- [ ] https://github.com/ArchiveTeam/Ubuntu-Warrior/issues/21

**Comment by reedy** [comment]
Any chance we could include https://github.com/ArchiveTeam/Ubuntu-Warrior/issues/21 in the mix? Whether as to help fix https://github.com/ArchiveTeam/Ubuntu-Warrior/issues/22 or just as a general enhancement for those using VMware based systems?

I suspect my PR at https://github.com/ArchiveTeam/Ubuntu-Warrior/pull/23 can almost be lifted verbatim into the right place...

**Comment by reedy** [comment]
https://github.com/ArchiveTeam/Ubuntu-Warrior/issues/5 is still seemingly relevant too...

Importing directly into esxi doesn't work

![esxi warrior 4 virutualhardwaresection](https://github.com/ArchiveTeam/warrior4-vm/assets/67615/19a2bc21-58d2-43ff-b1d5-67a7a8604b12)

Will have a play and see if the workarounds for the older version still work on the newer...

**Comment by chfoo** [comment]
> Any chance we could include [ArchiveTeam/Ubuntu-Warrior#21](https://github.com/ArchiveTeam/Ubuntu-Warrior/issues/21) in the mix? Whether as to help fix [ArchiveTeam/Ubuntu-Warrior#22](https://github.com/ArchiveTeam/Ubuntu-Warrior/issues/22) or just as a general enhancement for those using VMware based systems?

Adding open-vm-tools should be doable. I will add them soon.

For the unexpected shutdowns, the logic in version 3 appears to be incorrect and powers off the VM when it shouldn't. This new version properly queries the Docker container's health value and the seesaw-kit's reboot/shutdown requests.

**Comment by reedy** [comment]
> [ArchiveTeam/Ubuntu-Warrior#5](https://github.com/ArchiveTeam/Ubuntu-Warrior/issues/5) is still seemingly relevant too...
> 
> Importing directly into esxi doesn't work
> 
> ![esxi warrior 4 virutualhardwaresection](https://user-images.githubusercontent.com/67615/243867185-19a2bc21-58d2-43ff-b1d5-67a7a8604b12.PNG)
> 
> Will have a play and see if the workarounds for the older version still work on the newer...

Trying it on my ARM based mac into Fusion...

![Screenshot 2023-06-12 at 16 13 24](https://github.com/ArchiveTeam/warrior4-vm/assets/67615/b7c2903b-4fde-40f6-8215-4721f0c9921d)

Will try it on an intel device incase it's something related to that

**Comment by reedy** [comment]
Seems that OVF 2.0 doesn't work well (from a google)?

{f16a3b8db53c92e80f722d007118549a715c9b25}

**Comment by chfoo** [comment]
Maybe it would be simpler to provide VMDK disk images as well and instructions on how to set up port forwarding.

**Comment by reedy** [comment]
More than happy to help with testing/documentation :)

**Comment by chfoo** [comment]
A VMDK disk image is uploaded now. (It's compressed to a zip file so don't forget to unzip first.)

**Comment by chfoo** [comment]
Thank you for testing!

> This is probably a request for a different project... I don't know where that GUI comes from. But it would be nice if it just didn't say to connect on localhost :)

It is from this project. The message is just copied from version 3 which just assumes port forwarding is being used. I don't think we figured out how to automatically detect which VM network is being used yet.

**Comment by reedy** [comment]
Forked the IP display request into #5

**Comment by reedy** [comment]
https://github.com/ArchiveTeam/Ubuntu-Warrior/issues/22 definitely seems to be fixed.

Just logged into my "new" warrior, and noticed the upload/download figures were < 10GB each (but were well over 100).

Looks like it rebooted ~10 hours ago...

Not sure where this report wants to go..

```
2023-06-28 15:58:17,596 - seesaw.warrior - DEBUG - git operation: hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.

2023-06-28 15:58:17,598 - seesaw.warrior - DEBUG - Install complete hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.
```

**Comment by chfoo** [comment]
> [ArchiveTeam/Ubuntu-Warrior#22](https://github.com/ArchiveTeam/Ubuntu-Warrior/issues/22) definitely seems to be fixed.
> 
> Just logged into my "new" warrior, and noticed the upload/download figures were < 10GB each (but were well over 100).
> 
> Looks like it rebooted ~10 hours ago...

Thanks for testing, it looks like reboot requests for seesaw-kit is working.

**Comment by reedy** [comment]
Just rebuilt mine with the new `archiveteam-warrior-v4.0-20230722` image in a few minutes. All seems good! :)
